### ISSUE TITLE
NoMethodError: undefined method `equivalent_to?'

### ISSUE THREAD

**Issue by awead** [mbklein/equivalent-xml#25]
Ran into:
```
NoMethodError: undefined method `equivalent_to?'
```
When using with rspec.  I was able to fix this by adding `require 'equivalent-xml/rspec_matchers'` to my spec_helper.rb file.  I didn't have require either matchers or equivalent-xml as per the README.

This was using rspec 2.99 and rails 4.1.5.

**Comment by AmitPatel-BoTreeConsulting** [comment]
Facing same issue with `equivalent-xml 0.5.1`.  We have been using `RSpec 3.1.0` in one of our gem.

**Comment by mbklein** [comment]
This issue has been stagnant for a while, so I'm going to close it. I think the answer is to explicitly require `equivalent-xml/rspec_matchers` in `spec_helper.rb`.

**Comment by joallard** [comment]
@mbklein If that's the case I'd suggest trying to catch that with a more helpful error message. Error messages are important!

**Comment by jpmcgrath** [comment]
@mbklein it would be good to update the readme to reflect this.

**Comment by tierra** [comment]
Worth noting that this happens because matchers are only loaded if this gem detects that RSpec is defined:

```ruby
if defined?(::RSpec::Matchers) or defined?(::Spec::Matchers)
  require 'equivalent-xml/rspec_matchers'
end
```

But the issue here is that, anyone using the standard Ruby Coding Guidelines and Rubocop usually maintains a Gemfile that makes Bundler load `equivalent-xml` before it loads `rspec` (since it's in alphabetical order). Of course this means that, Rspec won't be loaded when EquivalentXml is loaded, so it thinks you don't need the matchers.

One way EquivalentXml could handle this situation (without requiring everyone to explicitly require the matchers) is by doing something like this:

```ruby
begin
  require 'rspec'
  require 'equivalent-xml/rspec_matchers'
rescue LoadError
end
```
