### ISSUE TITLE
option to log out where the difference is

### ISSUE THREAD

**Issue by Phuong5664** [mbklein/equivalent-xml#34]
Hi,

I'm new user of this gem, and also new to GitHup. This is not an issue, it's actually a request.
I just recently use this gem for my work project, it's working great, I love it.
It will be really helpful if the gem can show/print where the difference is?
Thanks for your time reading this.

Regards,
Phuong

**Comment by mbklein** [comment]
Hi Phuong,

The gem does yield each pair of nodes and a true/false match value during processing, but since matching is such a complex process, it's hard to know exactly what the output would look like. The best you can usually do is to supply a block and catch the first infringing node pair.

Michael

**Comment by Phuong5664** [comment]
Thank you so much for getting back to me Michael. I will try what you suggested and see.

Regards,
Phuong
